### ISSUE TITLE
https:localhost:8443 doesn't show anything

### ISSUE THREAD

**Issue by sillo1991** [SpyGuard/SpyGuard#9] opened 2023-02-07 10:23 UTC
I've tried the following commands on ubuntu and raspberry pi3b

cd /tmp/ && git clone https://github.com/SpyGuard/spyguard
cd spyguard && sudo bash install.sh

but just looks like there is nothing

**Comment by liuksovai** [comment] 2023-02-11 11:51
It's the same for me. When i try enter https://localhost:8443 the message shows that "This site can't be reached". 
(Raspberry Pi Desktop - bullseye 32bit.)

**Comment by colder1989** [comment] 2023-02-11 22:27
I think I solved the problem. The cause is that there was an update of Sqlalchemy which probably no longer accepts some arguments like for example "convert_unicode". For now the best thing is to install the old version. I uninstalled spyguard:

/usr/share/spyguard     sudo bash uninstall.sh
then sudo apt-get autoremove
then sudo reboot

 and reinstalled, but before doing "sudo bash install.sh" I modified the requirements.txt file:
 
/tmp/spyguard/assets        sudo nano requirements.txt


ipwhois
pydig
pymisp
netaddr
pyyaml
flask
flask_httpauth
pyjwt
sqlalchemy==1.4.45
psutil
pyudev
qrcode
netifaces
weasyprint
python-whois
publicsuffix2
six>=1.13.0

then ctrl+o and ctrl+x

now you can install with sudo bash install.sh on /tmp/spyguard

**Comment by liuksovai** [comment] 2023-02-13 22:12
Thanks for the help in solving this problem.

**Comment by fibrizho** [comment] 2023-06-08 15:40
I am experiencing the same issue. Installation logs:

`[+] Checking dependencies...
    [✘] tshark not installed, lets install it
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libbcg729-0 libc-ares2 liblua5.2-0 libsmi2ldbl libsnappy1v5 libspandsp2
  libssh-gcrypt-4 libwireshark-data libwireshark15 libwiretap12 libwsutil13
  wireshark-common
Suggested packages:
  snmp-mibs-downloader geoipupdate geoip-database geoip-database-extra
  libjs-leaflet libjs-leaflet.markercluster wireshark-doc
The following NEW packages will be installed:
  libbcg729-0 libc-ares2 liblua5.2-0 libsmi2ldbl libsnappy1v5 libspandsp2
  libssh-gcrypt-4 libwireshark-data libwireshark15 libwiretap12 libwsutil13
  tshark wireshark-common
0 upgraded, 13 newly installed, 0 to remove and 0 not upgraded.
Need to get 23,0 MB of archives.
After this operation, 120 MB of additional disk space will be used.
Get:1 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libbcg729-0 amd64 1.1.1-2 [32,9 kB]
Get:2 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 liblua5.2-0 amd64 5.2.4-2 [125 kB]
Get:3 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libsmi2ldbl amd64 0.4.8+dfsg2-16 [100 kB]
Get:4 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libspandsp2 amd64 0.0.6+dfsg-2 [272 kB]
Get:5 http://fr.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libssh-gcrypt-4 amd64 0.9.6-2ubuntu0.22.04.1 [222 kB]
Get:6 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libwireshark-data all 3.6.2-2 [1 647 kB]
Get:7 http://fr.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libc-ares2 amd64 1.18.1-1ubuntu0.22.04.1 [45,1 kB]
Get:8 http://fr.archive.ubuntu.com/ubuntu jammy/main amd64 libsnappy1v5 amd64 1.1.8-1build3 [17,5 kB]
Get:9 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libwsutil13 amd64 3.6.2-2 [99,2 kB]
Get:10 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libwiretap12 amd64 3.6.2-2 [255 kB]
Get:11 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libwireshark15 amd64 3.6.2-2 [19,5 MB]
Get:12 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 wireshark-common amd64 3.6.2-2 [473 kB]
Get:13 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 tshark amd64 3.6.2-2 [157 kB]
Fetched 23,0 MB in 9s (2 516 kB/s)                                             
Preconfiguring packages ...
Selecting previously unselected package libbcg729-0:amd64.
(Reading database ... 184631 files and directories currently installed.)
Preparing to unpack .../00-libbcg729-0_1.1.1-2_amd64.deb ...
Unpacking libbcg729-0:amd64 (1.1.1-2) ...
Selecting previously unselected package liblua5.2-0:amd64.
Preparing to unpack .../01-liblua5.2-0_5.2.4-2_amd64.deb ...
Unpacking liblua5.2-0:amd64 (5.2.4-2) ...
Selecting previously unselected package libsmi2ldbl:amd64.
Preparing to unpack .../02-libsmi2ldbl_0.4.8+dfsg2-16_amd64.deb ...
Unpacking libsmi2ldbl:amd64 (0.4.8+dfsg2-16) ...
Selecting previously unselected package libspandsp2:amd64.
Preparing to unpack .../03-libspandsp2_0.0.6+dfsg-2_amd64.deb ...
Unpacking libspandsp2:amd64 (0.0.6+dfsg-2) ...
Selecting previously unselected package libssh-gcrypt-4:amd64.
Preparing to unpack .../04-libssh-gcrypt-4_0.9.6-2ubuntu0.22.04.1_amd64.deb ...
Unpacking libssh-gcrypt-4:amd64 (0.9.6-2ubuntu0.22.04.1) ...
Selecting previously unselected package libwireshark-data.
Preparing to unpack .../05-libwireshark-data_3.6.2-2_all.deb ...
Unpacking libwireshark-data (3.6.2-2) ...
Selecting previously unselected package libc-ares2:amd64.
Preparing to unpack .../06-libc-ares2_1.18.1-1ubuntu0.22.04.1_amd64.deb ...
Unpacking libc-ares2:amd64 (1.18.1-1ubuntu0.22.04.1) ...
Selecting previously unselected package libsnappy1v5:amd64.
Preparing to unpack .../07-libsnappy1v5_1.1.8-1build3_amd64.deb ...
Unpacking libsnappy1v5:amd64 (1.1.8-1build3) ...
Selecting previously unselected package libwsutil13:amd64.
Preparing to unpack .../08-libwsutil13_3.6.2-2_amd64.deb ...
Unpacking libwsutil13:amd64 (3.6.2-2) ...
Selecting previously unselected package libwiretap12:amd64.
Preparing to unpack .../09-libwiretap12_3.6.2-2_amd64.deb ...
Unpacking libwiretap12:amd64 (3.6.2-2) ...
Selecting previously unselected package libwireshark15:amd64.
Preparing to unpack .../10-libwireshark15_3.6.2-2_amd64.deb ...
Unpacking libwireshark15:amd64 (3.6.2-2) ...
Selecting previously unselected package wireshark-common.
Preparing to unpack .../11-wireshark-common_3.6.2-2_amd64.deb ...
Unpacking wireshark-common (3.6.2-2) ...
Selecting previously unselected package tshark.
Preparing to unpack .../12-tshark_3.6.2-2_amd64.deb ...
Unpacking tshark (3.6.2-2) ...
Setting up libssh-gcrypt-4:amd64 (0.9.6-2ubuntu0.22.04.1) ...
Setting up libbcg729-0:amd64 (1.1.1-2) ...
Setting up libc-ares2:amd64 (1.18.1-1ubuntu0.22.04.1) ...
Setting up libspandsp2:amd64 (0.0.6+dfsg-2) ...
Setting up libsnappy1v5:amd64 (1.1.8-1build3) ...
Setting up libsmi2ldbl:amd64 (0.4.8+dfsg2-16) ...
Setting up libwsutil13:amd64 (3.6.2-2) ...
Setting up libwiretap12:amd64 (3.6.2-2) ...
Setting up libwireshark-data (3.6.2-2) ...
Setting up liblua5.2-0:amd64 (5.2.4-2) ...
Setting up libwireshark15:amd64 (3.6.2-2) ...
Setting up wireshark-common (3.6.2-2) ...
Setting up tshark (3.6.2-2) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for shared-mime-info (2.1-2) ...
    [✔] dig installed
    [✘] suricata not installed, lets install it
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libevent-2.1-7 libevent-core-2.1-7 libevent-pthreads-2.1-7 libhiredis0.14
  libhtp2 libhyperscan5 libluajit-5.1-2 libluajit-5.1-common libnet1
  libnetfilter-log1 libnetfilter-queue1 oinkmaster python3-simplejson
  snort-rules-default suricata-update
Suggested packages:
  snort | snort-pgsql | snort-mysql libtcmalloc-minimal4
The following NEW packages will be installed:
  libevent-2.1-7 libevent-core-2.1-7 libevent-pthreads-2.1-7 libhiredis0.14
  libhtp2 libhyperscan5 libluajit-5.1-2 libluajit-5.1-common libnet1
  libnetfilter-log1 libnetfilter-queue1 oinkmaster python3-simplejson
  snort-rules-default suricata suricata-update
0 upgraded, 16 newly installed, 0 to remove and 0 not upgraded.
Need to get 5 677 kB of archives.
After this operation, 27,8 MB of additional disk space will be used.
Get:1 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libhyperscan5 amd64 5.4.0-2 [2 485 kB]
Get:2 http://fr.archive.ubuntu.com/ubuntu jammy/main amd64 python3-simplejson amd64 3.17.6-1build1 [54,7 kB]
Get:3 http://fr.archive.ubuntu.com/ubuntu jammy/main amd64 libevent-2.1-7 amd64 2.1.12-stable-1build3 [148 kB]
Get:4 http://fr.archive.ubuntu.com/ubuntu jammy/main amd64 libevent-core-2.1-7 amd64 2.1.12-stable-1build3 [93,9 kB]
Get:5 http://fr.archive.ubuntu.com/ubuntu jammy/main amd64 libevent-pthreads-2.1-7 amd64 2.1.12-stable-1build3 [7 642 B]
Get:6 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libhiredis0.14 amd64 0.14.1-2 [32,8 kB]
Get:7 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libhtp2 amd64 1:0.5.39-1 [70,5 kB]
Get:8 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libluajit-5.1-common all 2.1.0~beta3+dfsg-6 [44,3 kB]
Get:9 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libluajit-5.1-2 amd64 2.1.0~beta3+dfsg-6 [238 kB]
Get:10 http://fr.archive.ubuntu.com/ubuntu jammy/main amd64 libnet1 amd64 1.1.6+dfsg-3.1build3 [46,9 kB]
Get:11 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libnetfilter-log1 amd64 1.0.2-1 [13,5 kB]
Get:12 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 libnetfilter-queue1 amd64 1.0.5-2 [14,4 kB]
Get:13 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 suricata amd64 1:6.0.4-3 [2 152 kB]
Get:14 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 oinkmaster all 2.0-4.1 [71,8 kB]
Get:15 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 snort-rules-default all 2.9.15.1-6build1 [146 kB]
Get:16 http://fr.archive.ubuntu.com/ubuntu jammy/universe amd64 suricata-update amd64 1.2.3-1 [56,7 kB]
Fetched 5 677 kB in 2s (2 403 kB/s)          
Preconfiguring packages ...
Selecting previously unselected package libhyperscan5.
(Reading database ... 185099 files and directories currently installed.)
Preparing to unpack .../00-libhyperscan5_5.4.0-2_amd64.deb ...
Unpacking libhyperscan5 (5.4.0-2) ...
Selecting previously unselected package python3-simplejson.
Preparing to unpack .../01-python3-simplejson_3.17.6-1build1_amd64.deb ...
Unpacking python3-simplejson (3.17.6-1build1) ...
Selecting previously unselected package libevent-2.1-7:amd64.
Preparing to unpack .../02-libevent-2.1-7_2.1.12-stable-1build3_amd64.deb ...
Unpacking libevent-2.1-7:amd64 (2.1.12-stable-1build3) ...
Selecting previously unselected package libevent-core-2.1-7:amd64.
Preparing to unpack .../03-libevent-core-2.1-7_2.1.12-stable-1build3_amd64.deb .
..
Unpacking libevent-core-2.1-7:amd64 (2.1.12-stable-1build3) ...
Selecting previously unselected package libevent-pthreads-2.1-7:amd64.
Preparing to unpack .../04-libevent-pthreads-2.1-7_2.1.12-stable-1build3_amd64.d
eb ...
Unpacking libevent-pthreads-2.1-7:amd64 (2.1.12-stable-1build3) ...
Selecting previously unselected package libhiredis0.14:amd64.
Preparing to unpack .../05-libhiredis0.14_0.14.1-2_amd64.deb ...
Unpacking libhiredis0.14:amd64 (0.14.1-2) ...
Selecting previously unselected package libhtp2.
Preparing to unpack .../06-libhtp2_1%3a0.5.39-1_amd64.deb ...
Unpacking libhtp2 (1:0.5.39-1) ...
Selecting previously unselected package libluajit-5.1-common.
Preparing to unpack .../07-libluajit-5.1-common_2.1.0~beta3+dfsg-6_all.deb ...
Unpacking libluajit-5.1-common (2.1.0~beta3+dfsg-6) ...
Selecting previously unselected package libluajit-5.1-2:amd64.
Preparing to unpack .../08-libluajit-5.1-2_2.1.0~beta3+dfsg-6_amd64.deb ...
Unpacking libluajit-5.1-2:amd64 (2.1.0~beta3+dfsg-6) ...
Selecting previously unselected package libnet1:amd64.
Preparing to unpack .../09-libnet1_1.1.6+dfsg-3.1build3_amd64.deb ...
Unpacking libnet1:amd64 (1.1.6+dfsg-3.1build3) ...
Selecting previously unselected package libnetfilter-log1:amd64.
Preparing to unpack .../10-libnetfilter-log1_1.0.2-1_amd64.deb ...
Unpacking libnetfilter-log1:amd64 (1.0.2-1) ...
Selecting previously unselected package libnetfilter-queue1:amd64.
Preparing to unpack .../11-libnetfilter-queue1_1.0.5-2_amd64.deb ...
Unpacking libnetfilter-queue1:amd64 (1.0.5-2) ...
Selecting previously unselected package suricata.
Preparing to unpack .../12-suricata_1%3a6.0.4-3_amd64.deb ...
Unpacking suricata (1:6.0.4-3) ...
Selecting previously unselected package oinkmaster.
Preparing to unpack .../13-oinkmaster_2.0-4.1_all.deb ...
Unpacking oinkmaster (2.0-4.1) ...
Selecting previously unselected package snort-rules-default.
Preparing to unpack .../14-snort-rules-default_2.9.15.1-6build1_all.deb ...
Unpacking snort-rules-default (2.9.15.1-6build1) ...
Selecting previously unselected package suricata-update.
Preparing to unpack .../15-suricata-update_1.2.3-1_amd64.deb ...
Unpacking suricata-update (1.2.3-1) ...
Setting up libnetfilter-log1:amd64 (1.0.2-1) ...
Setting up oinkmaster (2.0-4.1) ...
Setting up libhtp2 (1:0.5.39-1) ...
Setting up libnet1:amd64 (1.1.6+dfsg-3.1build3) ...
Setting up libhyperscan5 (5.4.0-2) ...
Setting up python3-simplejson (3.17.6-1build1) ...
Setting up libluajit-5.1-common (2.1.0~beta3+dfsg-6) ...
Setting up libevent-core-2.1-7:amd64 (2.1.12-stable-1build3) ...
Setting up libevent-2.1-7:amd64 (2.1.12-stable-1build3) ...
Setting up suricata-update (1.2.3-1) ...
Setting up libnetfilter-queue1:amd64 (1.0.5-2) ...
Setting up snort-rules-default (2.9.15.1-6build1) ...
Setting up libevent-pthreads-2.1-7:amd64 (2.1.12-stable-1build3) ...
Setting up libhiredis0.14:amd64 (0.14.1-2) ...
Setting up libluajit-5.1-2:amd64 (2.1.0~beta3+dfsg-6) ...
Setting up suricata (1:6.0.4-3) ...
Created symlink /etc/systemd/system/multi-user.target.wants/suricata.service → /
lib/systemd/system/suricata.service.
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
    [✘] sqlite3 not installed, lets install it
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  sqlite3-doc
The following NEW packages will be installed:
  sqlite3
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 768 kB of archives.
After this operation, 1 873 kB of additional disk space will be used.
Get:1 http://fr.archive.ubuntu.com/ubuntu jammy-updates/main amd64 sqlite3 amd64 3.37.2-2ubuntu0.1 [768 kB]
Fetched 768 kB in 0s (5 539 kB/s) 
Selecting previously unselected package sqlite3.
(Reading database ... 185373 files and directories currently installed.)
Preparing to unpack .../sqlite3_3.37.2-2ubuntu0.1_amd64.deb ...
Unpacking sqlite3 (3.37.2-2ubuntu0.1) ...
Setting up sqlite3 (3.37.2-2ubuntu0.1) ...
Processing triggers for man-db (2.10.2-1) ...
    [✘] pip, not installed, lets install it
    [✔] arp installed
[+] Install Python packages...
Requirement already satisfied: ipwhois==1.2.0 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: pydig==0.4.0 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 2)) (0.4.0)
Requirement already satisfied: pymisp==2.4.165.1 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 3)) (2.4.165.1)
Requirement already satisfied: netaddr==0.8.0 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 4)) (0.8.0)
Requirement already satisfied: pyyaml==5.3.1 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 5)) (5.3.1)
Requirement already satisfied: flask==1.1.2 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 6)) (1.1.2)
Requirement already satisfied: flask_httpauth==4.7.0 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 7)) (4.7.0)
Requirement already satisfied: pyjwt==1.7.1 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 8)) (1.7.1)
Collecting sqlalchemy==1.4.44
  Using cached SQLAlchemy-1.4.44-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Requirement already satisfied: psutil==5.8.0 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 10)) (5.8.0)
Requirement already satisfied: pyudev==0.24.0 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 11)) (0.24.0)
Requirement already satisfied: qrcode==7.3.1 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 12)) (7.3.1)
Requirement already satisfied: netifaces==0.11.0 in /usr/lib/python3/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 13)) (0.11.0)
Requirement already satisfied: weasyprint==57.1 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 14)) (57.1)
Requirement already satisfied: python-whois==0.8.0 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 15)) (0.8.0)
Requirement already satisfied: publicsuffix2==2.20191221 in /usr/local/lib/python3.10/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 16)) (2.20191221)
Requirement already satisfied: six==1.16.0 in /usr/lib/python3/dist-packages (from -r /tmp/spyguard/assets/requirements.txt (line 17)) (1.16.0)
Requirement already satisfied: dnspython<=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipwhois==1.2.0->-r /tmp/spyguard/assets/requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: publicsuffixlist<0.10.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (0.9.4)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.10/dist-packages (from pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (2.28.1)
Requirement already satisfied: jsonschema<5.0.0,>=4.17.0 in /usr/local/lib/python3.10/dist-packages (from pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (4.17.3)
Requirement already satisfied: deprecated<2.0.0,>=1.2.13 in /usr/local/lib/python3.10/dist-packages (from pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (1.2.14)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.10/dist-packages (from flask==1.1.2->-r /tmp/spyguard/assets/requirements.txt (line 6)) (2.1.2)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.10/dist-packages (from flask==1.1.2->-r /tmp/spyguard/assets/requirements.txt (line 6)) (2.3.5)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.10/dist-packages (from flask==1.1.2->-r /tmp/spyguard/assets/requirements.txt (line 6)) (3.1.2)
Requirement already satisfied: click>=5.1 in /usr/lib/python3/dist-packages (from flask==1.1.2->-r /tmp/spyguard/assets/requirements.txt (line 6)) (8.0.3)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy==1.4.44->-r /tmp/spyguard/assets/requirements.txt (line 9)) (2.0.2)
Requirement already satisfied: Pyphen>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (0.14.0)
Requirement already satisfied: Pillow>=9.1.0 in /usr/local/lib/python3.10/dist-packages (from weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (9.5.0)
Requirement already satisfied: cffi>=0.6 in /usr/local/lib/python3.10/dist-packages (from weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (1.15.1)
Requirement already satisfied: cssselect2>=0.1 in /usr/local/lib/python3.10/dist-packages (from weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (0.7.0)
Requirement already satisfied: pydyf>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (0.6.0)
Requirement already satisfied: fonttools[woff]>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (4.39.4)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (1.1)
Requirement already satisfied: tinycss2>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (1.2.1)
Requirement already satisfied: future in /usr/local/lib/python3.10/dist-packages (from python-whois==0.8.0->-r /tmp/spyguard/assets/requirements.txt (line 15)) (0.18.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=0.6->weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (2.21)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from cssselect2>=0.1->weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (0.5.1)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from deprecated<2.0.0,>=1.2.13->pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: zopfli>=0.1.4 in /usr/local/lib/python3.10/dist-packages (from fonttools[woff]>=4.0.0->weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (0.2.2)
Requirement already satisfied: brotli>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from fonttools[woff]>=4.0.0->weasyprint==57.1->-r /tmp/spyguard/assets/requirements.txt (line 14)) (1.0.9)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=2.10.1->flask==1.1.2->-r /tmp/spyguard/assets/requirements.txt (line 6)) (2.1.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema<5.0.0,>=4.17.0->pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (23.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema<5.0.0,>=4.17.0->pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (0.19.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.28.1->pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.28.1->pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (1.26.5)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.28.1->pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.28.1->pymisp==2.4.165.1->-r /tmp/spyguard/assets/requirements.txt (line 3)) (3.3)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.4.45
    Uninstalling SQLAlchemy-1.4.45:
      Successfully uninstalled SQLAlchemy-1.4.45
Successfully installed sqlalchemy-1.4.44
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[+] Changing the hostname to spyguard
[+] Generating SSL certificate for the backend
..+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.......+.....+.........+....+...+...+..+.........+....+.....................+...+..+.........+.+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+..........+...+.........+...............+..................+..+....+..+...+....+.....+..........+........+....+........................+......+....................+.+............+..+............................+......+......+....................+.+..+............+..........+........+.............+...+..+.......+...+..................+.....+.+...+..................+..+......+.........+............+.+..+......+...................+..+...+.....................+.+......+.....+....+......+..............+...+.+.........+.................+....+...........+.............+........+...+...............+......+...................+...........+.+..................+............+.....+....+.....+...+...+...............+....+........+......+.+.....+......+..........+.....+....+.....+....+............+............+.....+..........+...+..+............+....+............+.....+.........+.+.........+...+...........+...................+........+.......+...........+....+...........+.+.....+.+........+...............+......+....+...........+....+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.+..+...+.......+..+..........+........+..........+............+..+....+.....+.........+.+.....+.+...+..+.+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.......+.+......+...+......+......+..+..........+...............+..+.+...+..+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*......+...+....+.................+.+...+..+.........+.+..............+.............+.....+.+...........+.+..+......+......+.............+.....................+...........+.+.........+...+..+...+.............+........+..........+.....+........................+...+.........+.............+........+....+...........+..........+...+..+.......+.....+.+...........+..........+..................+........+...+................+.........+.....+............+...+....+...+..+.......+......+.........+......+..+...+....+...+..+...............+...+...............+.+.................+.......+...........+.......+...+.....+.+...+..+.+.........+.....+......+...+....+....................+.+.................+.........+....+......+.........+............+............+..+.........+................+...+...........+.......+.....+.......+..................+.........+........+................+.....................+........+.............+.....+...+.+.....+.+.........+...........+.......+........+...+.+......+.....+.............+..+.........+....+.....+.+........+............+...............+.+.....+...+....+.....+...+.........+.+...+...........+............................+......+..+.......+..+....+.....+.........+...+.......+..+.+..............+...............+.+..+.+..+.........+..........+........+.......+......+..+.+.....+................+........+............+.........................+........+..........+...........+..........+.....+.+........+.+..+...............+.............+..+...+..........+..............+......+.......+..+..........+..................+...+..+....+.......................................+..+.........+..........+........+.+......+.....+...+.+.....+............+.......+...............+......+.........+...+..+...+.............+......+...+........+..........+........+......+.+.........+.....+......+.........+....+................................+.......+.....+...+....+......+..+.+............+.........+.....+.........+.+...+...........+....+..+...+......................+..................+.....+.......+.....+...+.......+...+........+...+......+.........................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[+] Creating services
    [✔] Creating frontend service
    [✔] Creating backend service
    [✔] Creating watchers service
    [✔] Enabling services
    [✔] Starting services
[+] Feeding your SpyGuard instance with fresh IOCs and whitelist, please wait.
[+] Installation finished! You can open https://localhost:8443 to configure network settings.`

When opening https://localhost:8443... Unable to connect...

The installation has been done on Ubuntu 22.04

Any help to try and debug/fix the issue would be highly appreciated.

**Comment by b068931cc450442b63f5b3d276ea4297** [comment] 2024-01-20 12:11
Hi,
@fibrizho I have edited your last post. You can use ``` before and after a code block to get a better view.

With the current code I have just tested it successfully on a system with Linux Mint, you can try it out to see if it works for you now. If not, please open a new issue.

**Closed by b068931cc450442b63f5b3d276ea4297** 2024-01-20 12:11 UTC
